sudo: required

language: generic

branches:
  only:
    - master

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t hgstudy/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true hgstudy/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app-2"
  env: "Docker-react-app-2-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-154920292787"
  bucket_path: "docker-react-app-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY